version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - libusb-1.0.0-dev

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
